### ISSUE TITLE
進行役として各回答者の正解・不正解を入力して、各回答者の正答数を管理(画面に表示)したい

### ISSUE THREAD

**Issue by amatsuda** [asakusarb/hayaoshi#4]
ジャストアイデアです。あ、べつに @yancya さんに実装しろ、って言ってるわけじゃありませんよ。
もちろん実装するな、とも言ってませんが。

**Comment by yancya** [comment]
SE の事を考えたときに、正解不正解もいるよなと考えてました
そんなに大変では無さそうですね

**Comment by yancya** [comment]
「不正解（お手つき）で１回休み」も欲しくなりますね

**Comment by amatsuda** [comment]
> 「不正解（お手つき）で１回休み」も欲しくなりますね

いいすね！

**Comment by yancya** [comment]
機能入ったので閉じます
